#include "forth.h"
void hard_load(){
unsigned int write_location = HERE, temp_last = 0;
extern void ret();
extern void call();
extern void emit();
extern void dot();
extern void ok();
extern void plus();
extern void minus();
extern void times();
extern void divide();
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = 'e'; write_location++;
*((char*) write_location) = 'm'; write_location++;
*((char*) write_location) = 'i'; write_location++;
*((char*) write_location) = 't'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &emit; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = '.'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &dot; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = 'o'; write_location++;
*((char*) write_location) = 'k'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &ok; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = '+'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &plus; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = '-'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &minus; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = '*'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &times; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = '/'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &divide; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
R_LAST = temp_last; temp_last = 0;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = 'e'; write_location++;
*((char*) write_location) = 'x'; write_location++;
*((char*) write_location) = 'i'; write_location++;
*((char*) write_location) = 't'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
*((unsigned int*) write_location) = temp_last; temp_last = write_location; write_location += 4;
*((char*) write_location) = 'd'; write_location++;
*((char*) write_location) = 'o'; write_location++;
*((char*) write_location) = 'c'; write_location++;
*((char*) write_location) = 'o'; write_location++;
*((char*) write_location) = 'l'; write_location++;
*((unsigned int*) write_location) = (unsigned int) &call; write_location += 4;
*((unsigned int*) write_location) = (unsigned int) &ret; write_location += 4;
C_LAST = temp_last;}
